### ISSUE TITLE
the default value of various features

### ISSUE THREAD

**Issue by baoqianyue** [ebbywiselyn/android-sensor#1]
How do you get the default values of the music and speech features in the audio classification in calculating the knn distance，as well as the default value in the user activities classification。  

Appreciate you!

**Comment by ebbywiselyn** [comment]
Hello there. 

Sorry I am not sure it's been too long. We referred to some research papers, https://www.tik.ee.ethz.ch/file/ecf9bf3e550dafdd10181f1ca6d08538/extremecom11_twimight.pdf this is one of the research that started after we worked on this project. You might want to check out those references listed.

**Comment by ebbywiselyn** [comment]
Found it https://www.cs.dartmouth.edu/~sensorlab/pubs/s3_mobisys09.pdf  We took the defaults from this paper, and maybe tuned the rest of the params.

**Comment by baoqianyue** [comment]
Thanks
